#!/usr/bin/env bash
# Writes its PID to a file, loops forever, and reacts differently to
# SIGINT, SIGTERM, and SIGQUIT

echo $$ > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT

while true; do
echo "To infinity and beyond"
sleep 2
done
