#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely, but reacts to SIGTERM
# instead of dying from it
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
echo "To infinity and beyond"
sleep 2
done
